modLoader = "javafml"
loaderVersion = "[38,)"
license = "MIT License"

[[mods]]
modId = "hydrogenmod"
version = "1.1.0"
displayName = "HydrogenMod"
displayURL = "https://github.com/stouma915/HydrogenMod"
credits = "Idea by bikikiMK2, Programmed by stouma915, Block model by Blockbench"
authors = "stouma915, bikikiMK2"
description = "水素で遊ぼう"

[[dependencies.hydrogenmod]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hydrogenmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"
